import './useReservationStore.seating.integration.test'
import './useReservationStore.assignment.integration.test'
import './useReservationStore.walkin.integration.test'
import './useReservationStore.merge.integration.test'
import './useReservationStore.dense.integration.test'
import './useReservationStore.property.integration.test'
